---
- name: Configure extended ACL for Requirement 2
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Load new ACL into device
      ios_config:
        parents: ip access-list extended REQ2
        lines:
          - permit icmp host 192.168.20.20 host 192.168.10.10 echo
          - permit icmp host 192.168.10.10 any echo-reply
          - deny icmp any any echo
          - permit ip any any

    - name: Apply new ACL to R1 interface
      ios_config:
        parents: interface <interface_name> # Замените <interface_name> на имя интерфейса, к которому применяется ACL
        lines:
          - ip access-group REQ2 in

    - name: Check result
      ios_command:
        commands: sh ip access-lists REQ2
      register: result
      tags: show

    - name: Print result
      debug:
        var: result.stdout_lines
      tags: show
